### ISSUE TITLE
YAML Parser: Allow premises to be lists as well as maps

### ISSUE THREAD

**Issue by tfgordon** [carneades/carneades-4#14]
Currently the premises of an argument scheme (unlike arguments) must be a map, with role names as keys, in the YAML format of argument graphs.  Let's extend the parser to also allow the premises to be listed, without role names.  Use the index of each premise in the list ("1", "2", ...) as its role name in this case.  (Using "1" for the first premise, rather than "0", is probably more intuitive for our intended users.)

**Comment by tfgordon** [comment]
Hasn't this been done, Horst?

**Comment by hfried** [comment]
done
