### ISSUE TITLE
Problem evaluating walton.yml example

### ISSUE THREAD

**Issue by jmatsushita** [carneades/carneades-4#23]
Hi there,

When running the following command after a fresh go get:
```
~/go/bin/carneades eval -t yaml ~/go/src/github.com/carneades/carneades-4/examples/AGs/YAML/walton.yml                                                                                                                                               
```

The output seems truncated with an empty `argument` key:

```
meta:
    notes: "Here we illustrate one way to represent many of the argumentation schemes of Doug Walton, including critical questions.
"
    source: "Walton, Douglas and Reed, Chris and Macagno, Fabrizio (2008).  Argumentation Schemes. Cambridge University Press.
"
    title: Walton Argumentation Schemes
issues:
statements:
    in_domain(¬caused_by(global_warming,humans),climate):
        text: "The claim that global warming is not caused by humans is in the climate domain.
"
        label: in
    asserts(joe,¬caused_by(global_warming,humans)):
        text: "Joe asserts that global warming is not caused by humans.
"
        label: in
    ¬caused_by(global_warming,humans):
        text: "Global warming is not caused by humans.
"
        label: out
    based_on_evidence(asserts(joe,¬caused_by(global_warming,humans))):
        text: "Joe's assertion is based on evidence."
        label: out
    expert(joe,climate):
        text: Joe is a climate expert.
        label: in
assumptions:
    - biased(joe)
    - expert(joe,climate)
    - asserts(joe,¬caused_by(global_warming,humans))
    - in_domain(¬caused_by(global_warming,humans),climate)
arguments:
```

The problem doesn't seem to occur on the web service though, so it's probably a regression, although my "go-fu" is not up to par to build an earlier version of the package. Just curious, which version is the current web service running ? (would be awesome to show the commit hash in the frontend somehow in addition to the version).

Cheers,

Jun

**Comment by jmatsushita** [comment]
FYI, running the new `check` command seems to return without an error
```
 ~/go/bin/carneades check -f yaml ~/go/src/github.com/carneades/carneades-4/examples/AGs/YAML/walton.yml
```

**Comment by tfgordon** [comment]
Dear Jun,


Are you the founder of iilab?  If, so please give my regards to Pierre.

I am glad to see you are interested in Carneades.


Anyway, I will try to get to bottom of the problem you identified and will

update the Carneades server soon.  Showing the commit hash is a nice

idea.  I'll add this to the issue tracker.


I will get back to you as soon as the problem is fixed.


Yours,


Tom


________________________________

**Comment by tfgordon** [comment]
Great!  If there is anything else I can do to help, please let me know.  Perhaps we could meet, if you are interested.  Anyway, the bug should be fixed now.  And the server of the web version is running the most recent commit.  Please confirm before I close this issue.

**Comment by jmatsushita** [comment]
It seems that the problem came from SWI prolog not being installed properly! Maybe a small check in `carneades eval` would help identify this human error?
