### ISSUE TITLE
Argument weights need to be displayed with greater precision

### ISSUE THREAD

**Issue by tfgordon** [carneades/carneades-4#9]
Argument weights are displayed currently with only one digit after the decimal point.  At least 2 digits after the decimal point should be shown.

**Comment by hfried** [comment]
erledigt

Von: Tom Gordon [mailto:notifications@github.com]
Gesendet: Donnerstag, 10. September 2015 11:12
An: carneades/carneades-4
Betreff: [carneades-4] Argument weights need to be displayed with greater precision (#9)


Argument weights are displayed currently with only one digit after the decimal point. At least 2 digits after the decimal point should be shown.

**Comment by tfgordon** [comment]
Danke Horst!  Läuft schon auf carneades.fokus.fraunhofer.de.  Tom
